### ISSUE TITLE
TypeError when running

### ISSUE THREAD

**Issue by IrenXu** [kukionfr/VAMPIRE_open#4]
Hi,

I've been trying this package but there is a type error that I do not know how to correct it.

Even if I am using the example data, it shows like this:
## collect_selected_bstack.py
CSV file is empty
Exception in Tkinter callback
Traceback (most recent call last):
  File "c:\users\dell\anaconda3\envs\cancer_tutorial\lib\tkinter\__init__.py", line 1702, in __call__
    return self.func(*args)
  File "c:\users\dell\anaconda3\envs\cancer_tutorial\lib\site-packages\vampireanalysis\vampire.py", line 124, in <lambda>
    b3 = Button(rows[6], text='build model', width=12, command=(lambda e=ents: Model(e, True, progress_bar)))
  File "c:\users\dell\anaconda3\envs\cancer_tutorial\lib\site-packages\vampireanalysis\vampire.py", line 82, in Model
    mainbody(buildModel, csv, entries, outpth, clnum, progress_bar)
  File "c:\users\dell\anaconda3\envs\cancer_tutorial\lib\site-packages\vampireanalysis\mainbody.py", line 35, in mainbody
    bdpc, vampire_model = bdreg(bstack[0], N, vampire_model, build_model)
TypeError: 'NoneType' object is not subscriptable
![image](https://user-images.githubusercontent.com/77282283/104198868-ac377600-541e-11eb-9673-903db8518eb7.png)

Would you mind checking this out?

Many thanks!
Yilin

**Comment by kukionfr** [comment]
Thank you for reporting this. I was able to reproduce this error in the pip installed version of the code. 
This issue is resolved in the newer version of the software (version 3.4.4) 
Please upgrade using "pip install vampireanalysis --upgrade" and let me know if the issue persists.

**Comment by IrenXu** [comment]
Hi, that typeerroe is fixed thanks a lot!
but there appears another problem:
![image](https://user-images.githubusercontent.com/77282283/104492438-88656300-55cb-11eb-80a2-0f224ef47bb9.png)
Does this mean there is something wrong with my input? It's a one row thing, the input has to be two rows?
